### ISSUE TITLE
BOM missing u4/u5

### ISSUE THREAD

**Issue by thbreidenbach** [OlegMishin/GotekFlashFloppy#1]
Hey, wondered if missing u4/u5 is on purpose for maybe another hardware revision. I ordered them from the Schematics but since there's no design files it's also a bit hard to always find the right footprints for ICs. Maybe you could either give access to design files or add more information to the BOM.
Great work anyways!! Ordered 3 PCB and will give feedback!!

**Comment by OlegMishin** [comment]
Hi,
U4/U5 are optional components to implement Amiga's external drive circuit(I've updated the schematics with such comment). As FlashFloppy supports this feature in firmware, U4/U5 are not needed. The  ICs and other components which shall be not mounted marked as DNP on the schematics.
Please follow the BOM for components ordering and assembly. 

Thanks for your feedback!

BR
Oleg
