### ISSUE TITLE
Need a fully assembled PCB

### ISSUE THREAD

**Issue by danko79** [OlegMishin/GotekFlashFloppy#3]
Hi Oleg, i'm Juri from Italy, i find your project and really interesting, would you have an assembled PCB for sale?
sorry but i didn't know how to contact you.
Regards

**Comment by OlegMishin** [comment]
Hi Juri, nice to meet you.

Sorry, I don't have assembled pcb for sale. At least for the revision 0. There are some upcoming changes towards revision 1, I'm going order some pcbs for testing and some of them perhaps will be available for sale. I will update the project's information here when it is ready but can not promise it will be soon.
Could you please have a look at the "Revision 1" files and let me know if you have any coments.

Thanks!

Regards
Oleg
