### ISSUE TITLE
Rotary Encoder weird working

### ISSUE THREAD

**Issue by nosyn00b** [OlegMishin/GotekFlashFloppy#5]
Hi Oleg,
   I successfully assembled your version of Gotek Flash Floppy with great satisfaction. I assembled it from scratch using the old PCB revision - the one without dip switches - because I had just ordered the old PCBs version when you uploaded the new one :-(.

Thanks for your excellent work, after some issues with an Amiga/PC modified drive, that caused all attempt to read an ADF fail even if I could see all files, I finally saw this little miracle working "simply" unplugging the internal drive (in this way I discovered what I purchased some months ago :-)).

But I have a weird problem with the rotary encoder: to make it "work" I had to use "rotary=buttons, half" or(!) "rotary=half, v2" options parameter in the FF.CFG file. Still, after playing with all parameters, I can only proceed forward in the menu items, there is no way to go backward. I checked the PCB tracks for shorts one million time but it's all as it should be according to the schematics. Do you have any suggestion to try solving this (apart purchasing and trying with a different encoder). Do you know if it makes sense to change some other parameter (eg the default twobutton-action=zero). Or perhaps, this is the "by design" behavior with your Gotek version?

Thanks for your support.

**Comment by OlegMishin** [comment]
Hi nosyn00b,

Thanks for assembling my proect. As this project is absolutely the same as usual Gotek in the eccoder connection, most likely the problem is at the encoder's side. Working on this project I have never had any issues with the encoder using default settings of FlashFloppy firmware. I used chinese  noname and Bourns PEC11R encoders. No issues.
I would recommend to double check the encoder you have: pinout, connections etc. If you share its part number or datasheet, I can have a look.

Regards
Oleg

**Comment by nosyn00b** [comment]
I used a cheap chinese one [here](https://www.aliexpress.com/item/4000285265971.html), but I did not have any problem with other similar projects with the sibling rotary encoders I purchased in the set. 

If you did not have problems with the default settings, I definetly suspect the single one I used to be defective... will try with another one, and check if something changes before going with an expensive Bourn :)

I'll let you know. Thanks really much for your really quick answer!

**Comment by nosyn00b** [comment]
Hi Oleg, I confirm the problem was a false contact on the microprocessor pin. When testing I inconsciously pressed a bit the pin and so it made contact, but when not pressed the contact was no more there. Sorry for disturbing you with this issue. Now the standard encorder works flowlessly.
