### ISSUE TITLE
Setup Rev.1 Question

### ISSUE THREAD

**Issue by venice1200** [OlegMishin/GotekFlashFloppy#7]
Hi,
this is not an issue, more a question how to setup the board for df1 usage.

I got a Rev.1 PCB assembled and FlashFloppy 3.41 installed.
Display, USB and Rotary are working but the board is not detected by my Amiga 500.

Do I only need to close the „jumper“ for drive 1 to activate the board for df1?

![IMG_9967](https://github.com/OlegMishin/GotekFlashFloppy/assets/43762187/ab695b62-5c11-45a5-bbd0-b70c7483026f)

Many thanks for this compact Gotek Drive.

**Comment by venice1200** [comment]
Full Board View

![IMG_9968](https://github.com/OlegMishin/GotekFlashFloppy/assets/43762187/fdc9ca22-e961-41e6-a371-9ed868f32a72)

**Comment by OlegMishin** [comment]
Hi,
Correct, only DIP "1" shall be ON for Amiga's Drive 1. If there is no issues in soldering it should work. I would recommend to clean the pcb with isopropanol. It looks a bit dirty.

**Comment by venice1200** [comment]
It looks like cleaning does the job as I don't find anything wrong and the board works now.

But is it correct that the LED is (s)lightly blinking all the time even the drive is not accessed?

See:

https://github.com/OlegMishin/GotekFlashFloppy/assets/43762187/e5c33d22-e26a-4733-8af2-41b048c1ded9

**Comment by OlegMishin** [comment]
I see the same blinking in my boards but only when Kickstart is about to boot from it. After loading, e.g. AmigaTestKit, no more blinking.

**Comment by venice1200** [comment]
The blinking is controlled by the MCU or by the Amiga or from both together?

**Comment by OlegMishin** [comment]
It is controled by Amiga(Drive Select function).

**Comment by venice1200** [comment]
I tested using an Amiga 500 with Kick 1.3
I will test an A1200 as well.

**Comment by opengiveback** [comment]
Hi, congratulations on this great de:sign, and thank you for making it opensource.

I made Revision 1 boards also, and have one assembled and working, but also have a question. Is it possible to use the "Revision 1" PCB based device as DF0: ? I have used a normal gotek before, flashed with FlashFloppy and with an external gotek adapter, and when I set jumper S1, it was DF1:, when I set S0 instead, it became DF0: when I unplug internal floppy, on the external port also.

But **these dip switches start with 1? When I set "1" as on, it acts as DF1: , so how would I get this to be DF0: ?** When the internal drive is not connected, of course.

P.S. I intend to build more and also sell these, and give back 15% of profits to the author(s of hardware and software), as per my opengiveback.org idea. I believe everyone should give back to the authors of products built for sale from open source, so if you have any email for paypal donations, or other means of donating to you preferred by you, please let me know.

**Comment by venice1200** [comment]
From my Amiga understanding you can use DF0 only internally without any modification's.

Means, you need the Rev.0 Adapter PCB and set it to Drive 0 to use it internally as DF0, if the Adapter can work with Rev.1. The Board himself should be configurred as Drive 1.

If you want to use DF0 externally you need a switch (Boot selector) which swaps the drive enable signals between DF0 and DF1.

If I am wrong correct me please.

**Comment by venice1200** [comment]
Oleg, my issue is solved, feel free to close it.

**Comment by OlegMishin** [comment]
Hi @opengiveback,
Thanks for your comment. Regarding DF0 @venice1200 absolutely right. It is not possible, at least in usual way, to use the external Gotek as DF0 as there is no DF0 select signal on Amiga's external floppy connector. Maybe it would be possible using MOTOR_ON but I have neve tried. You can find a Boot Selector project in my repository, which does DF0-DF1 swap.

I use DIP switch markings starting from "1" to math Amiga's floppy count order. As I mentioned above, an external floppy starts from "1". You can compare the below circuits to see it is the same in a Drive Select part:
Gotek:
![image](https://github.com/OlegMishin/GotekFlashFloppy/assets/81614352/a6765741-0dc2-4284-b31a-3ffdd4340760)

GotekFlashFloppy:
![image](https://github.com/OlegMishin/GotekFlashFloppy/assets/81614352/a6a861a6-795b-481d-914c-fff9ba3d8866)


I like your Opengiveback idea and don't mind to participate. I wouldn't like to share my email openly, so if it is ok for you, could you contact me via PM or LinkedIn message.

@venice1200, glad you solve it :)

Regards
Oleg
